name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Dependency Review'
        uses: greenbone/actions/dependency-review@cdaf49a9913e2944bfb5ebc1e333acadaeb3d16d # v3.36.15
