name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Dependency Review'
        uses: greenbone/actions/dependency-review@41ce222ededcb84b9ee4f4b532083c69de062a01 # v3.36.13
