name: SBOM upload
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  SBOM-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: 'SBOM upload'
        uses: greenbone/actions/sbom-upload@41ce222ededcb84b9ee4f4b532083c69de062a01 # v3.36.13
