name: SBOM upload
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  SBOM-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: 'SBOM upload'
        uses: greenbone/actions/sbom-upload@80a38a10bb7eb2b3c12f7f0361532dc6120342d6 # v3.36.20
